### ISSUE TITLE
Provide more flexibility when chaining operations

### ISSUE THREAD

**Issue by BendyWalker** [3squared/PeakNetwork#3]
`DecodableOperation` is useful, but has a very narrow use case. Either allow it to be subclassed to provide more flexibility when building chains of operations, or make a version that implements `ConsumesResult`.

**Comment by blork** [comment]
Yeah, if you want to perform a request based on the output of a previous request it can be quite clunky. I think making more of the operations `open` is needed too. @bendywalker If you could make a pull request with an example of how you think this should work, that would be awesome; otherwise I’ll add this as my next thing to do.
